
name: Publish Github experimental
on:
  push:
    branches:    
      - experimental
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@britishgas-engineering'
    - run: npm install
    - run: echo "registry=https://npm.pkg.github.com/@britishgas-engineering" >> .npmrc
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}